[build]
  command = "npm run build"  # El comando para construir tu proyecto Next.js
  publish = ".next"          # La carpeta que contiene la salida de la construcción
  functions = "netlify/functions" # La carpeta donde se encuentran las funciones serverless

[[redirects]]
from = '/_next/image/*'
query = { q = ':quality', url = ':url', w = ':width' }
to = '/.netlify/images?url=:url&w=:width&q=:quality'
status = 200
force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"  